<<<<<<< HEAD
# Generated by Django 2.0 on 2020-07-25 17:03
=======
# Generated by Django 2.0 on 2020-07-25 12:43
>>>>>>> d77c8f17a2ae35f3f7df9eab3215b105e2dbcfe1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default='customer', max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('mobile_no', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=400, null=True)),
                ('openhours', models.CharField(max_length=30, null=True)),
                ('latitude', models.CharField(max_length=30, null=True)),
                ('longitude', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default='customer', max_length=30)),
>>>>>>> d77c8f17a2ae35f3f7df9eab3215b105e2dbcfe1
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('mobile_no', models.CharField(max_length=12)),
<<<<<<< HEAD
                ('address', models.CharField(max_length=400, null=True)),
=======
                ('category', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=400, null=True)),
                ('openhours', models.CharField(max_length=30, null=True)),
>>>>>>> d77c8f17a2ae35f3f7df9eab3215b105e2dbcfe1
                ('latitude', models.CharField(max_length=30, null=True)),
                ('longitude', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
